apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "wakala-platform.labels" . | nindent 4 }}
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: "workload=general"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "wakala-platform.fullname" . }}-quota
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    requests.cpu: "100"
    requests.memory: "200Gi"
    requests.storage: "2Ti"
    persistentvolumeclaims: "50"
    services.loadbalancers: "2"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "wakala-platform.fullname" . }}-limits
  namespace: {{ .Release.Namespace }}
spec:
  limits:
  - default:
      cpu: "2"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - max:
      storage: "500Gi"
    type: PersistentVolumeClaim