{{- if .Values.secrets.provider }}
---
# External Secrets Operator SecretStore
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "wakala-platform.fullname" . }}-secret-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    {{- if eq .Values.secrets.provider "aws-secrets-manager" }}
    aws:
      service: SecretsManager
      region: {{ .Values.global.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "wakala-platform.serviceAccountName" . }}
    {{- else if eq .Values.secrets.provider "vault" }}
    vault:
      server: {{ .Values.secrets.vault.address }}
      path: {{ .Values.secrets.vault.path }}
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: {{ include "wakala-platform.fullname" . }}
          serviceAccountRef:
            name: {{ include "wakala-platform.serviceAccountName" . }}
    {{- end }}
---
# Database credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.postgresql.auth.existingSecret }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "wakala-platform.fullname" . }}-secret-store
    kind: SecretStore
  target:
    name: {{ .Values.postgresql.auth.existingSecret }}
    creationPolicy: Owner
  data:
  - secretKey: postgres-password
    remoteRef:
      key: wakala/database/postgres
      property: password
  - secretKey: postgres-replication-password
    remoteRef:
      key: wakala/database/postgres
      property: replication-password
---
# Redis credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.redis.auth.existingSecret }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "wakala-platform.fullname" . }}-secret-store
    kind: SecretStore
  target:
    name: {{ .Values.redis.auth.existingSecret }}
    creationPolicy: Owner
  data:
  - secretKey: redis-password
    remoteRef:
      key: wakala/redis
      property: password
---
# RabbitMQ credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.rabbitmq.auth.existingPasswordSecret }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "wakala-platform.fullname" . }}-secret-store
    kind: SecretStore
  target:
    name: {{ .Values.rabbitmq.auth.existingPasswordSecret }}
    creationPolicy: Owner
  data:
  - secretKey: rabbitmq-password
    remoteRef:
      key: wakala/rabbitmq
      property: password
  - secretKey: rabbitmq-erlang-cookie
    remoteRef:
      key: wakala/rabbitmq
      property: erlang-cookie
---
# JWT signing keys
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "wakala-platform.fullname" . }}-jwt-keys
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: {{ include "wakala-platform.fullname" . }}-secret-store
    kind: SecretStore
  target:
    name: {{ include "wakala-platform.fullname" . }}-jwt-keys
    creationPolicy: Owner
  data:
  - secretKey: private-key
    remoteRef:
      key: wakala/jwt
      property: private-key
  - secretKey: public-key
    remoteRef:
      key: wakala/jwt
      property: public-key
---
# API keys for third-party services
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "wakala-platform.fullname" . }}-api-keys
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "wakala-platform.fullname" . }}-secret-store
    kind: SecretStore
  target:
    name: {{ include "wakala-platform.fullname" . }}-api-keys
    creationPolicy: Owner
  data:
  - secretKey: whatsapp-api-key
    remoteRef:
      key: wakala/api-keys
      property: whatsapp
  - secretKey: twilio-api-key
    remoteRef:
      key: wakala/api-keys
      property: twilio
  - secretKey: sendgrid-api-key
    remoteRef:
      key: wakala/api-keys
      property: sendgrid
  - secretKey: stripe-api-key
    remoteRef:
      key: wakala/api-keys
      property: stripe
  - secretKey: paypal-api-key
    remoteRef:
      key: wakala/api-keys
      property: paypal
---
# Encryption keys
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "wakala-platform.fullname" . }}-encryption-keys
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: {{ include "wakala-platform.fullname" . }}-secret-store
    kind: SecretStore
  target:
    name: {{ include "wakala-platform.fullname" . }}-encryption-keys
    creationPolicy: Owner
  data:
  - secretKey: master-key
    remoteRef:
      key: wakala/encryption
      property: master-key
  - secretKey: data-key
    remoteRef:
      key: wakala/encryption
      property: data-key
{{- end }}