apiVersion: v2
name: wakala-platform
description: Helm chart for Wakala Mobile Money Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - wakala
  - mobile-money
  - fintech
  - microservices
home: https://wakala.platform
sources:
  - https://github.com/wakala/platform
maintainers:
  - name: Wakala DevOps Team
    email: devops@wakala.platform
dependencies:
  - name: postgresql
    version: 12.1.9
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.3.17
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: rabbitmq
    version: 11.3.2
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: elasticsearch
    version: 19.5.14
    repository: https://charts.bitnami.com/bitnami
    condition: elasticsearch.enabled