{{- if .Values.apiGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wakala-platform.fullname" . }}-api-gateway
  labels:
    {{- include "wakala-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
  {{- with .Values.apiGateway.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.apiGateway.service.type }}
  ports:
  - port: {{ .Values.apiGateway.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: 9090
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "wakala-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
{{- end }}